"""Public interfaces for the smart-ask routing application."""

from .application import SmartAsk
from .domain import (
    Attempt,
    Context,
    ExecutionRequest,
    ModelResult,
    RouteResult,
    RoutingEvent,
    RunResult,
    Task,
)
from .executors import HermesExecutor, ModelExecutor, OpenRouterExecutor
from .methods import (
    CascadeRoutingMethod,
    DifficultyClassification,
    DifficultyClassifier,
    DifficultyRoutingMethod,
    EscalationDecision,
    EscalationPolicy,
    FixedRoutingMethod,
    LLMDifficultyClassifier,
    MarkerEscalationPolicy,
    RoutingMethod,
)
from .strategy import (
    LoadedStrategy,
    StrategyBuildError,
    StrategyBuilder,
    StrategyConfig,
    StrategyConfigError,
    load_strategy,
)
from .metrics import (
    CallStats,
    RunStats,
    StatsCollector,
    StatsSummary,
    ResourceReport,
    TaskOutcome,
    TokenUsage,
    aggregate_resources,
    aggregate_stats,
)

__all__ = [
    "Attempt",
    "CallStats",
    "CascadeRoutingMethod",
    "Context",
    "DifficultyClassification",
    "DifficultyClassifier",
    "DifficultyRoutingMethod",
    "EscalationDecision",
    "EscalationPolicy",
    "ExecutionRequest",
    "FixedRoutingMethod",
    "HermesExecutor",
    "LLMDifficultyClassifier",
    "LoadedStrategy",
    "MarkerEscalationPolicy",
    "ModelExecutor",
    "ModelResult",
    "OpenRouterExecutor",
    "RouteResult",
    "RoutingEvent",
    "RoutingMethod",
    "RunResult",
    "RunStats",
    "ResourceReport",
    "SmartAsk",
    "StrategyBuildError",
    "StrategyBuilder",
    "StrategyConfig",
    "StrategyConfigError",
    "StatsCollector",
    "StatsSummary",
    "TaskOutcome",
    "Task",
    "TokenUsage",
    "aggregate_stats",
    "aggregate_resources",
    "load_strategy",
]
